//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLiteCoinTester.BfEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.balances = new HashSet<balance>();
            this.transactions = new HashSet<transaction>();
        }
    
        public int uid { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string description { get; set; }
        public string avatarUrl { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> addressid { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<balance> balances { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
